// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfeIawrXfaOeXvc4V3oX7_-eYY1e-kQ4',
    appId: '1:880633877376:web:58627807ffd8694bd56765',
    messagingSenderId: '880633877376',
    projectId: 'desafioqw',
    authDomain: 'desafioqw.firebaseapp.com',
    storageBucket: 'desafioqw.appspot.com',
    measurementId: 'G-RSLHESTBGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1gTHdj8aCWEIJpCe-HW9uBBQCxjDfIc',
    appId: '1:880633877376:android:c30e985201a6e336d56765',
    messagingSenderId: '880633877376',
    projectId: 'desafioqw',
    storageBucket: 'desafioqw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChTNpffHZODF8hNVeMsHIZX_Xa2eYyCJM',
    appId: '1:880633877376:ios:bf8b13148329f369d56765',
    messagingSenderId: '880633877376',
    projectId: 'desafioqw',
    storageBucket: 'desafioqw.appspot.com',
    iosClientId: '880633877376-sv9do6b7cv5bu3mt7r1e2t9ojdfrjk84.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChTNpffHZODF8hNVeMsHIZX_Xa2eYyCJM',
    appId: '1:880633877376:ios:bf8b13148329f369d56765',
    messagingSenderId: '880633877376',
    projectId: 'desafioqw',
    storageBucket: 'desafioqw.appspot.com',
    iosClientId: '880633877376-sv9do6b7cv5bu3mt7r1e2t9ojdfrjk84.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafio',
  );
}
